# Generated by Django 4.2.7 on 2024-01-06 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ur_landmark', models.CharField(max_length=100, null=True)),
                ('ur_locality', models.CharField(max_length=100, null=True)),
                ('ur_city', models.CharField(max_length=100, null=True)),
                ('ur_state', models.CharField(max_length=100, null=True)),
                ('ur_country', models.CharField(max_length=100, null=True)),
                ('ur_pin', models.IntegerField(null=True)),
                ('ur_phone', models.BigIntegerField(null=True)),
                ('ur_DOB', models.DateField(null=True)),
                ('ur_pic', models.ImageField(null=True, upload_to='image/')),
                ('ur_bio', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
