# Generated by Django 4.2.7 on 2024-01-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadmin', '0002_alter_user_profile_ur_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noti_msg', models.CharField(max_length=255)),
                ('noti_status', models.BooleanField(default=1)),
            ],
        ),
    ]
