# Generated by Django 4.2.7 on 2024-01-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadmin', '0007_admin_messages_msg_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_messages',
            name='msg_subject',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
