# Generated by Django 4.2.7 on 2024-01-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadmin', '0008_admin_messages_msg_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='ur_campus',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='ur_course',
            field=models.CharField(max_length=220, null=True),
        ),
    ]
