# Generated by Django 4.2.7 on 2024-01-06 14:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_postedon', models.DateTimeField(default=datetime.datetime(2024, 1, 6, 19, 59, 49, 509820))),
                ('job_title', models.TextField(max_length=100)),
                ('company_name', models.TextField(max_length=100)),
                ('job_location', models.TextField(max_length=100)),
                ('job_category', models.TextField()),
                ('job_package', models.TextField()),
                ('job_type', models.TextField()),
                ('job_deadline', models.DateTimeField(blank=True, null=True)),
                ('job_description', models.TextField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
