# Generated by Django 4.2.7 on 2024-01-06 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobportal',
            name='job_postedon',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 20, 0, 19, 970458)),
        ),
    ]
