# Generated by Django 4.2.7 on 2024-01-14 12:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0006_remove_user_posts_pt_likes_user_posts_pt_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_posts',
            name='pt_likes',
        ),
        migrations.CreateModel(
            name='post_likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_on', models.DateTimeField(default=datetime.datetime.now)),
                ('liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.user_posts')),
            ],
        ),
    ]
