# Generated by Django 4.2.7 on 2024-01-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_remove_user_posts_pt_likes_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_likes',
            name='like',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
