# Generated by Django 4.2.7 on 2024-01-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_user_posts_pt_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_posts',
            name='pt_comment',
            field=models.IntegerField(default=0),
        ),
    ]
