# Generated by Django 4.2.7 on 2024-01-26 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadmin', '0006_admin_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_messages',
            name='msg_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
