# Generated by Django 4.2.7 on 2023-12-30 05:37

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPortal',
            fields=[
                ('job_id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('job_postedon', models.DateTimeField(default=datetime.datetime(2023, 12, 30, 11, 7, 53, 437736))),
                ('job_title', models.TextField(max_length=100)),
                ('company_name', models.TextField(max_length=100)),
                ('job_location', models.TextField(max_length=100)),
                ('job_category', models.TextField()),
                ('job_package', models.TextField()),
                ('job_type', models.TextField()),
                ('job_deadline', models.DateTimeField(blank=True, null=True)),
                ('job_description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('taskid', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('task_title', models.TextField(max_length=255)),
                ('task_description', models.TextField(null=True)),
                ('task_created_on', models.DateTimeField(default=datetime.datetime(2023, 12, 30, 11, 7, 53, 437736))),
                ('task_completed_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
