# Generated by Django 4.2.7 on 2023-12-30 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToDoList',
        ),
        migrations.AlterField(
            model_name='jobportal',
            name='job_postedon',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 30, 11, 20, 59, 486358)),
        ),
    ]
