# Generated by Django 4.2.7 on 2024-01-06 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_jobportal_job_postedon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobportal',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobportal',
            name='job_category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobportal',
            name='job_description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobportal',
            name='job_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobportal',
            name='job_package',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobportal',
            name='job_postedon',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='jobportal',
            name='job_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobportal',
            name='job_type',
            field=models.CharField(max_length=100),
        ),
    ]
