# Generated by Django 4.2.7 on 2024-01-12 04:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0003_alter_jobportal_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_on', models.DateTimeField(default=datetime.datetime.now)),
                ('pt_content', models.TextField(blank=True, max_length=255, null=True)),
                ('pt_media', models.FileField(blank=True, null=True, upload_to='userposts/')),
                ('pt_status', models.BinaryField(default=True)),
                ('pt_likes', models.BigIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='post_comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_comment', models.CharField(max_length=225)),
                ('comment_on', models.DateTimeField(default=datetime.datetime.now)),
                ('comment_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.user_posts')),
            ],
        ),
    ]
